### ISSUE TITLE
Issues with display of 'marking status' tables

### ISSUE THREAD

**Issue by tim3dwards** [fernandooliveira/moodle-block_marking_manager#41]
Hi NED guys,

First off, thanks kindly for the awesome plugin!

We've discovered a problem with the 'marking status' tables that get put together to show correct / incorrect answers for a quiz. Only correct answers get added to the table, questions manually graded as incorrect (and description type questions) don't get included in the table as I presume they should.

As such, the ticks for correct answers do not line up with the relevant questions on the 'marking status' page. 

If you look at the attached screenshot, the top half shows how a quiz was manually graded. You'll see there's 4 description type questions throughout the quiz. The first 5 gradable questions were marked '0', the last 5 marked '1'. 

Now, look at the bottom half of the screenshot, which shows the table Marking Manager created to depict these scores. You'll notice only the correct answers are displayed, and do not correspond with the relevant questions. Below, in the orange outline, is a table I quickly mocked up in Photoshop which shows how I would expect the table to be displayed. 

Moodle version - 3.3.2+ (Build: 20170922)
Theme - Boost
NED Marking manager version - 3.3.1 (2017083001)

Hope that's of use, let me know if you've got any questions about this.

Thanks,

Tim.

![ned-marking-manager-issue](https://user-images.githubusercontent.com/32676371/31392126-598e46f6-add0-11e7-824d-eed48d1bd5a2.jpg)

**Comment by fernandooliveira** [comment]
Hi Tim, Thanks for the screenshots. This issues is fixed in latest version.

**Comment by tim3dwards** [comment]
Fantastic, many thanks! When will the new version be released, please?

Best wishes,

Tim.

**Comment by fernandooliveira** [comment]
Yesterday

**Comment by tim3dwards** [comment]
Great, thanks. I’ve installed the following build  - block_fn_marking_moodle33_2017101200

Unfortunately the issue still exists in this release of the plugin too, nothing seems to have changed (see screenshot below). Aside from updating the plugin in Moodle, is there anything else we need to do?

[cid:image001.jpg@01D34436.DDDEDF50]

Kind regards,

Tim.

**Comment by fernandooliveira** [comment]
Can you try to clear your cache? If that doesn't work, please post your screenshot again. I can't see it in your previous message.

**Comment by tim3dwards** [comment]
Yeah, cached was cleared fully (cookies / site data / cached images and files).

I’ll post up a screenshot on the bug tracker page for you.

Thanks,

Tim.

**Comment by tim3dwards** [comment]
I cleared Chrome browser cache in its entirety, and also purged the cache in Moode. Below is a screenshot using build 33_20171001200

![image](https://user-images.githubusercontent.com/32676371/31553286-e439ccd6-b031-11e7-8a1d-c913aa566a05.png)

**Comment by fernandooliveira** [comment]
Hi Tim, please test latest Github code to see if this resolves this issue.

**Comment by tim3dwards** [comment]
Hiya,

That seems to have done the job, it’s working exactly as expected now.

Many thanks,

Tim.
